# Generated by Django 5.2.8 on 2025-11-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BRAZIL', 'Brasil'), ('CANADA', 'Canadá'), ('FRANCE', 'França'), ('GERMANY', 'Alemanha'), ('ITALY', 'Itália'), ('SPAIN', 'Espanha'), ('AUSTRALIA', 'Austrália'), ('CHINA', 'China'), ('INDIA', 'Índia'), ('JAPAN', 'Japão')], max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Actors',
        ),
    ]
