# Generated by Django 5.2.8 on 2025-11-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_actor_delete_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('GERMANY', 'Alemanha'), ('ARGENTINA', 'Argentina'), ('AUSTRALIA', 'Austrália'), ('AUSTRIA', 'Áustria'), ('BELGIUM', 'Bélgica'), ('BRAZIL', 'Brasil'), ('CANADA', 'Canadá'), ('CHINA', 'China'), ('DENMARK', 'Dinamarca'), ('SPAIN', 'Espanha'), ('USA', 'Estados Unidos'), ('FRANCE', 'França'), ('INDIA', 'Índia'), ('ITALY', 'Itália'), ('JAPAN', 'Japão'), ('MEXICO', 'México'), ('UK', 'Reino Unido'), ('CZECH_REPUBLIC', 'República Tcheca')], max_length=100, null=True),
        ),
    ]
