# Generated by Django 5.2.8 on 2025-11-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_alter_actor_nationality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('name',)},
        ),
    ]
